spring:
  datasource:
    url: ${REGISTER_DB_URL:jdbc:postgresql://postgres:5432/rxlog}
    username: ${REGISTER_DB_USER:rxlog}
    password: ${REGISTER_DB_PASSWORD:rxlog}
    driver-class-name: org.postgresql.Driver



  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration